const ADD_TODO = "ADD_TODO";
const DONE_TODO = "DONE_TODO";
const DELETE_TODO = "DELETE_TODO";
const RETURN_TODO = "RETURN_TODO";
const SET_TODOSDONE = "SET_TODOSDONE";
const SET_TODOS = "SET_TODOS";

export {
  ADD_TODO,
  DONE_TODO,
  DELETE_TODO,
  RETURN_TODO,
  SET_TODOSDONE,
  SET_TODOS,
};
